# Etapa 1: Construção da Aplicação com Maven
FROM maven AS build

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o arquivo pom.xml e baixar as dependências
COPY pom.xml .

# Baixar as dependências do Maven (cache de dependências)
RUN mvn dependency:go-offline -B

# Copiar o código fonte para o contêiner
COPY src ./src

# Empacotar a aplicação (gerar o JAR)
RUN mvn clean package -DskipTests

# Renomear o JAR para um nome fixo
RUN mv target/main-*.jar target/main.jar

# Etapa 2: Executar a Aplicação com OpenJDK
FROM openjdk

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o JAR da etapa de build para a imagem final
COPY --from=build /app/target/main.jar app.jar

# Expor a porta que a aplicação irá usar (ajuste se necessário)
EXPOSE 8080

# Definir o perfil ativo como "prod" dentro do container
ENV SPRING_PROFILES_ACTIVE=prod

# Definir o comando para executar a aplicação
ENTRYPOINT ["java","-jar","app.jar"]
